In [1]:
import numpy as np

In [15]:
# Ejercicio 1. 

#Actividades
# 1.Convierte la lista en un array de NumPy y reorganízalo como una matriz de 4 × 6. 
#2.Muestra su tipo de dato, número de dimensiones y forma. 
#3.Calcula el total vendido en cada turno y el total vendido de cada producto. 
#4.Identifica el turno con mayor cantidad total de ventas. 
#5.Obtén una copia con todas las ventas incrementadas en 2 unidades y verifica que la matriz original no 
#cambió.  

ventas = [18, 12, 25, 10, 8, 15, 
20, 14, 22, 13, 11, 17, 
16, 19, 27, 9, 12, 18, 
24, 17, 21, 15, 10, 20] 

ventas_matriz = np.array(ventas)
#1
ventas_matriz = ventas_matriz.reshape((4,6))
print('='*20)
#2
print(ventas_matriz.dtype) #tipo de datos
print(ventas_matriz.ndim) #numero de dimensiones
print(ventas_matriz.shape) #filas de columnas
print('='*20)
#3
venta_total_turno = ventas_matriz.sum(axis=1)
print(venta_total_turno)
print('='*20)

venta_total_producto = ventas_matriz.sum(axis=0)
print(venta_total_producto)
print('='*20)

#4
print(venta_total_turno.argmax())
print('='*20)

#5
ventas_incrementadas = ventas_matriz + 2
print(ventas_incrementadas)
print(ventas_matriz)

int64
2
(4, 6)
[ 88  97 101 107]
[78 62 95 47 41 70]
3
[[20 14 27 12 10 17]
 [22 16 24 15 13 19]
 [18 21 29 11 14 20]
 [26 19 23 17 12 22]]
[[18 12 25 10  8 15]
 [20 14 22 13 11 17]
 [16 19 27  9 12 18]
 [24 17 21 15 10 20]]


In [ ]:
# EJERCICIO 2

stock = np.array(
    [
        [25, 18, 30, 12, 20], 
        [14, 22, 16, 28, 19], 
        [35, 17, 24, 15, 21]
    ]
) 

ventas = np.array(
    [
        [10, 20, 12, 8, 7], 
        [16, 10, 18, 9, 20], 
        [15, 19, 8, 17, 11]
    ]
) 


#1.Calcula el inventario restante mediante una operación entre matrices.
stock_restante = stock - ventas 
print (stock_restante)
print('='*20)

#2.Localiza los valores negativos, que representan ventas mayores al stock disponible.
mascara = stock_restante < 0
print(stock_restante[mascara])
print('='*20)

#3.Crea una copia corregida en la que los valores negativos sean reemplazados por 0.
stock_restante_corregido = stock_restante.copy()
stock_restante_corregido[mascara] = 0
print(stock_restante_corregido)
print('='*20)

#4.Calcula el stock restante total por categoría antes y después de la corrección.
stock_restante_antes = stock_restante.sum(axis=1)
print(stock_restante_antes)
print('='*20)
stock_restante_despues = stock_restante_corregido.sum(axis=1)
print(stock_restante_despues)
print('='*20)


#5.Determina la categoría con mayor stock disponible después de la corrección. 
max_valor = total.max()


[[15 -2 18  4 13]
 [-2 12 -2 19 -1]
 [20 -2 16 -2 10]]
[-2 -2 -2 -1 -2 -2]
[[15  0 18  4 13]
 [ 0 12  0 19  0]
 [20  0 16  0 10]]
[48 26 42]
[50 31 46]
1


In [ ]:
precios = np.array([[4.5, 6.0, 3.5, 8.0], 
                    [4.7, 5.8, 3.6, 8.2], 
                    [4.6, 6.1, 3.4, 7.9]]) 
 
unidades = np.array([[30, 18, 42, 15], 
                     [25, 20, 35, 17], 
                     [28, 22, 40, 14]]) 
#Actividades
 
#1.Calcula la facturación por producto y sucursal mediante multiplicación elemento a elemento.
total = precios * unidades
print(total)
print('='*20)
#2.Calcula la facturación total de cada sucursal y la facturación total de cada producto. 


#3.Identifica la sucursal con mayor facturación. 


#4.Encuentra el valor máximo de facturación individual y su posición dentro de la matriz.
posicion = np.unravel_index(np.argmax(total), total.shape)
print(max_valor, posicion)
print('='*20) 
#5.Obtén la transpuesta de la matriz de facturación e interpreta qué representan ahora sus filas. 

[[135.  108.  147.  120. ]
 [117.5 116.  126.  139.4]
 [128.8 134.2 136.  110.6]]
147.0 (np.int64(0), np.int64(2))
