In [1]:
import numpy as np
print(np.__version__)


2.5.1


In [3]:
array = np.array([1,2,3,5])

array * 2

array([ 2,  4,  6, 10])

In [4]:
lista = [1,2,3,5]

arr_lista = np.array(lista)
print(arr_lista)
print(type(arr_lista))

arr_lista * 2

[1 2 3 5]
<class 'numpy.ndarray'>


array([ 2,  4,  6, 10])

In [5]:
arr_lista.dtype

dtype('int64')

In [6]:
lista_decimales = [1.0,2.1,2.4,5.6]

arr_lista = np.array(lista_decimales)
arr_lista.dtype

dtype('float64')

In [8]:
lista = [1,2,3,5]

arr_lista = np.array(lista, dtype='float64')
print(arr_lista)
print(arr_lista.dtype)

[1. 2. 3. 5.]
float64


CONVERTIR TIPO DE DATOS DE MI ARRAY

In [9]:
lista = [1,2,3,5]

arr_lista = np.array(lista)
print(arr_lista)
arr_lista.dtype

[1 2 3 5]


dtype('int64')

In [10]:
arr_float = arr_lista.astype('float64')
print(arr_float)
arr_float.dtype

[1. 2. 3. 5.]


dtype('float64')

In [11]:
arr_str = arr_lista.astype('str')
print(arr_str)
arr_str.dtype

['1' '2' '3' '5']


dtype('<U21')

DIMENSIONES

In [13]:
# SCALAR

scalar = np.array(50)
print(scalar)
print(type(scalar))
print(scalar.ndim)

50
<class 'numpy.ndarray'>
0


In [14]:
#VECTOR

vector = np.array([1,2,3,5])
print(vector.ndim)

1


In [17]:
# MATRIZ
matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


GENERACION DE NUMEROS ALEATORIOS

In [18]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.zeros(5,dtype='int64')

array([0, 0, 0, 0, 0])

In [21]:
np.zeros((5,5),dtype='int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.ones((10,10), dtype='int64')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
np.ones((3,10,2), dtype='int64')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])